#!/bin/bash
#
# Build the Tier-2 ESP32-S3 satellite firmware (dawn_satellite_arduino) from the
# command line via arduino-cli — the same compile the Arduino IDE runs, scripted
# so it works the same locally and in CI.  See docs/OTA_DESIGN.md §8.
#
# Usage:
#   ./build-esp32.sh              install core+libs (idempotent), then compile + export the .bin
#   ./build-esp32.sh --stub       also generate PLACEHOLDER gitignored headers if MISSING
#                                 (ca_cert.h / arduino_secrets.h / ota_pubkey.h) so a fresh
#                                 checkout compiles — for the CI compile gate.  Never overwrites a
#                                 real header.  A --stub build is a COMPILE CHECK ONLY: the .bin
#                                 carries placeholder WiFi/CA/key and is NOT flashable.
#   ./build-esp32.sh --compile-only   skip the core/lib install (fast re-compile)
#
# A real, flashable release .bin is built by the operator WITHOUT --stub, after
# dropping in real ca_cert.h / arduino_secrets.h / ota_pubkey.h; feed that .bin to
#   sudo ../dawn_satellite/ota-release.sh --platform esp32 --tier 2 --abi-tag esp32s3 --image <bin>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKETCH_DIR="$SCRIPT_DIR"

# ── Single source of truth: board + libraries (shared by local runs and CI) ───
ESP32_INDEX="https://espressif.github.io/arduino-esp32/package_esp32_index.json"
# Adafruit Feather ESP32-S3 TFT, with the Tools-menu settings the sketch needs:
# QSPI PSRAM, 4 MB flash, "Minimal SPIFFS (1.9MB APP with OTA)" (== partitions.csv).
# This board is an ESP32-S3R2 (2 MB QSPI PSRAM) — PSRAM=enabled is the board's
# default and the CORRECT mode.  PSRAM=opi maps zero PSRAM on this chip
# (psramFound() still returns true but getPsramSize()==0, so ps_malloc fails) —
# do NOT use opi here.
FQBN="esp32:esp32:adafruit_feather_esp32s3_tft:PSRAM=enabled,FlashSize=4M,PartitionScheme=min_spiffs"
LIBS=(
   "WebSockets"                         # Markus Sattler / Links2004
   "ArduinoJson"
   "Adafruit GFX Library"
   "Adafruit ST7735 and ST7789 Library"
   "Adafruit NeoPixel"
)
APP_SLOT_BYTES=$((0x1E0000)) # min_spiffs app slot; warn if the image exceeds ~85%

STUB=0
COMPILE_ONLY=0
for arg in "$@"; do
   case "$arg" in
      --stub) STUB=1 ;;
      --compile-only) COMPILE_ONLY=1 ;;
      -h | --help)
         sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
         exit 0
         ;;
      *)
         echo "build-esp32: unknown option: $arg" >&2
         exit 1
         ;;
   esac
done

die() {
   echo "build-esp32: $*" >&2
   exit 1
}

command -v arduino-cli >/dev/null 2>&1 ||
   die "arduino-cli not found — install: https://arduino.github.io/arduino-cli/latest/installation/"

# ── Placeholder headers so a fresh checkout compiles (compile gate only).
#    Created ONLY when missing — never clobbers a real, provisioned header. ────
if [ "$STUB" -eq 1 ]; then
   [ -f "$SKETCH_DIR/arduino_secrets.h" ] ||
      { cp "$SKETCH_DIR/arduino_secrets.h.example" "$SKETCH_DIR/arduino_secrets.h" &&
         echo "build-esp32: stubbed arduino_secrets.h"; }
   [ -f "$SKETCH_DIR/ota_pubkey.h" ] ||
      { cp "$SKETCH_DIR/ota_pubkey.h.example" "$SKETCH_DIR/ota_pubkey.h" &&
         echo "build-esp32: stubbed ota_pubkey.h"; }
   if [ ! -f "$SKETCH_DIR/ca_cert.h" ]; then
      cat > "$SKETCH_DIR/ca_cert.h" <<'STUB_CA'
/* PLACEHOLDER from build-esp32.sh --stub — compile gate only, NOT a real CA.
 * The real ca_cert.h is generated by generate_ssl_cert.sh on the daemon host. */
#ifndef CA_CERT_H
#define CA_CERT_H
static const char CA_CERT_PEM[] PROGMEM = R"PEM(
-----BEGIN CERTIFICATE-----
PLACEHOLDER0PLACEHOLDER0PLACEHOLDER0PLACEHOLDER0PLACEHOLDER0PLACEH
OLDER0PLACEHOLDER0PLACEHOLDER0PLACEHOLDER0PLACEHOLDER0PLACEHOLDER0
-----END CERTIFICATE-----
)PEM";
#endif
STUB_CA
      echo "build-esp32: stubbed ca_cert.h"
   fi
fi

# ── Toolchain + libraries (idempotent; cheap to re-run once installed) ─────────
if [ "$COMPILE_ONLY" -eq 0 ]; then
   echo "==> installing esp32 core + libraries (idempotent)…"
   arduino-cli core update-index --additional-urls "$ESP32_INDEX"
   arduino-cli core install esp32:esp32 --additional-urls "$ESP32_INDEX"
   for lib in "${LIBS[@]}"; do
      arduino-cli lib install "$lib"
   done
fi

# ── Compile + export the .bin (pipefail propagates a compile failure) ──────────
echo "==> compiling $FQBN"
log="$(mktemp)"
trap 'rm -f "$log"' EXIT
arduino-cli compile --fqbn "$FQBN" --warnings default --export-binaries "$SKETCH_DIR" 2>&1 | tee "$log"

bin="$(find "$SKETCH_DIR/build" -name '*.ino.bin' 2>/dev/null | head -1)"
[ -n "$bin" ] || die "compile produced no .bin"

# Size advisory against the app slot (the hard limit is enforced by the linker;
# this flags creeping toward the slot before OTA headroom gets tight).
used="$(grep -oE 'Sketch uses [0-9]+ bytes' "$log" | grep -oE '[0-9]+' | head -1 || true)"
if [ -n "${used:-}" ]; then
   pct=$((used * 100 / APP_SLOT_BYTES))
   echo "==> image ${used} bytes = ${pct}% of the ${APP_SLOT_BYTES}-byte app slot"
   [ "$pct" -ge 85 ] &&
      echo "build-esp32: WARNING: image >85% of the app slot — trim before relying on OTA headroom" >&2
fi

echo "==> done: $bin"
[ "$STUB" -eq 1 ] && echo "    (--stub: placeholder headers — COMPILE CHECK ONLY, not flashable)"
exit 0
